# Generated by Django 4.2.1 on 2023-06-05 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f78359da-b3f8-42a3-8424-482e28a20c93'), primary_key=True, serialize=False),
        ),
    ]
