# Generated by Django 4.2.1 on 2023-06-14 21:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=1000)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-postdate'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('cuisine', models.CharField(default='Null', max_length=50)),
                ('category', models.CharField(default='Uncategorized', max_length=50)),
                ('level', models.CharField(default='Null', max_length=50)),
                ('servings', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('method', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ingredients', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('nutrition', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('featureimage', models.ImageField(upload_to='core/recipes/%Y/%m/')),
                ('publishdate', models.DateField()),
                ('tags', models.CharField(default='Untagged', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipes',
                'ordering': ['-publishdate'],
            },
        ),
    ]
