# Generated by Django 4.2.1 on 2023-06-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recipe_duration_alter_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='publishdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
