# Generated by Django 4.2.1 on 2023-06-05 11:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=1000)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-postdate'],
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'cuisines',
            },
        ),
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('BR', 'Breakfast'), ('LN', 'Lunch'), ('DN', 'Dinner')], max_length=10)),
                ('slug', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'recipe_types',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('ingredients', models.CharField(blank=True, max_length=1000, null=True)),
                ('cooking_duration', models.PositiveIntegerField(default=0)),
                ('cooking_method', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('featureimage', models.ImageField(upload_to='core/article/%Y/%m/')),
                ('publishdate', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuisines', to='core.cuisine')),
                ('recipe_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='core.cuisinetype')),
            ],
            options={
                'db_table': 'recipes',
                'ordering': ['-publishdate'],
            },
        ),
    ]
