# Generated by Django 4.2.1 on 2023-06-15 00:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e4a48a49-7876-43a8-b378-911109179a49'), primary_key=True, serialize=False),
        ),
    ]
