# Generated by Django 4.2.1 on 2023-06-15 00:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('af9ff58a-b526-4312-b3d9-f1ac21beea38'), primary_key=True, serialize=False),
        ),
    ]
