# Generated by Django 4.2.1 on 2023-06-15 23:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f48496d4-6918-493e-86cb-1e5f67e70781'), primary_key=True, serialize=False),
        ),
    ]
